import type {ColorTheme, SemanticColorTokens} from './types';

export const lightThemeColorTokenByRole: SemanticColorTokens = {
  'brand-primary': 'orange500',
  'brand-primary-pressed': 'orange700',
  'brand-secondary': 'navy500',
  'background-variant-1': 'gray60',
  'background-variant-2': 'white',
  'surface-layer': 'white',
  'surface-elevation-1': 'white',
  'surface-elevation-2': 'gray20',
  'surface-elevation-3': 'gray40',
  'surface-gnb': 'white',
  'surface-gnb-gray': 'gray900',
  'surface-footer': 'gray880',
  'surface-highlight': 'orange50',
  'surface-fab': 'white',
  'surface-fab-pressed': 'gray100',
  'inverse-elevation-1': 'black/30',
  'inverse-elevation-2': 'black/15',
  'inverse-elevation-3': 'black/10',
  'inverse-elevation-4': 'black/8',
  'inverse-elevation-5': 'black/6',
  'inverse-elevation-6': 'black/4',
  'inverse-elevation-7': 'black/10',
  'inverse-elevation-8': 'black/2',
  'inverse-variant-1': 'black/30',
  'inverse-variant-2': 'black/15',
  'inverse-variant-3': 'black/6',
  'interaction-pressed': 'black/10',
  'interaction-selected': 'black/8',
  'interaction-focused': 'black/8',
  'interaction-hover': 'black/4',
  'disabled-variant-1': 'gray200',
  'disabled-variant-2': 'gray150',
  'disabled-variant-3': 'gray80',
  'disabled-variant-4': 'gray40',
  'disabled-variant-5': 'gray200',
  'disabled-variant-6': 'gray80',
  'disabled-variant-7': 'white/20',
  'disabled-variant-8': 'black/8',
  'on-surface-elevation-1': 'gray880',
  'on-surface-elevation-1-pressed': 'black',
  'on-surface-elevation-2': 'gray800',
  'on-surface-elevation-2-pressed': 'gray880',
  'on-surface-elevation-3': 'gray600',
  'on-surface-elevation-3-pressed': 'gray700',
  'on-surface-elevation-4': 'gray400',
  'on-surface-elevation-4-pressed': 'gray500',
  'neutral-variant-1': 'gray700',
  'neutral-variant-1-pressed': 'gray800',
  'neutral-variant-2': 'gray40',
  'neutral-variant-2-pressed': 'gray80',
  'neutral-variant-3': 'white',
  'neutral-variant-3-pressed': 'gray40',
  'neutral-variant-4': 'gray150',
  'border': 'gray150',
  'placeholder': 'gray300',
  'error': 'system-red',
  'warning': 'system-yellow',
  'success': 'system-green',
  'information': 'system-blue',
};

export const darkThemeColorTokenByRole: SemanticColorTokens = {
  'brand-primary': 'orange500',
  'brand-primary-pressed': 'orange300',
  'brand-secondary': 'navy500',
  'background-variant-1': 'gray900',
  'background-variant-2': 'gray880',
  'surface-layer': 'gray780',
  'surface-elevation-1': 'gray840',
  'surface-elevation-2': 'gray820',
  'surface-elevation-3': 'gray800',
  'surface-gnb': 'gray900',
  'surface-gnb-gray': 'gray900',
  'surface-footer': 'black',
  'surface-highlight': 'white/10',
  'surface-fab': 'gray750',
  'surface-fab-pressed': 'gray650',
  'inverse-elevation-1': 'white/30',
  'inverse-elevation-2': 'white/15',
  'inverse-elevation-3': 'white/10',
  'inverse-elevation-4': 'white/8',
  'inverse-elevation-5': 'white/6',
  'inverse-elevation-6': 'white/4',
  'inverse-elevation-7': 'white/4',
  'inverse-elevation-8': 'white/2',
  'inverse-variant-1': 'white/15',
  'inverse-variant-2': 'white/6',
  'inverse-variant-3': 'white/4',
  'interaction-pressed': 'white/10',
  'interaction-selected': 'white/8',
  'interaction-focused': 'white/8',
  'interaction-hover': 'white/4',
  'disabled-variant-1': 'gray650',
  'disabled-variant-2': 'gray650',
  'disabled-variant-3': 'gray750',
  'disabled-variant-4': 'gray500',
  'disabled-variant-5': 'gray200',
  'disabled-variant-6': 'gray80',
  'disabled-variant-7': 'white/20',
  'disabled-variant-8': 'white/10',
  'on-surface-elevation-1': 'gray80',
  'on-surface-elevation-1-pressed': 'white',
  'on-surface-elevation-2': 'gray200',
  'on-surface-elevation-2-pressed': 'gray80',
  'on-surface-elevation-3': 'gray300',
  'on-surface-elevation-3-pressed': 'gray100',
  'on-surface-elevation-4': 'gray500',
  'on-surface-elevation-4-pressed': 'gray300',
  'neutral-variant-1': 'gray600',
  'neutral-variant-1-pressed': 'gray400',
  'neutral-variant-2': 'gray800',
  'neutral-variant-2-pressed': 'gray700',
  'neutral-variant-3': 'gray840',
  'neutral-variant-3-pressed': 'gray750',
  'neutral-variant-4': 'gray650',
  'border': 'gray650',
  'placeholder': 'gray600',
  'error': 'system-red',
  'warning': 'system-yellow',
  'success': 'system-green',
  'information': 'system-blue',
};

export const getSemanticColorToken = (args?: {colorTheme: ColorTheme}) => {
  const {colorTheme = 'light'} = args ?? {};

  return colorTheme === 'dark'
    ? darkThemeColorTokenByRole
    : lightThemeColorTokenByRole;
};

export * from './types';
