import type {Color} from '../../global-tokens';

export type ColorRole =
  | 'brand-primary'
  | 'brand-primary-pressed'
  | 'brand-secondary'
  | 'background-variant-1'
  | 'background-variant-2'
  | 'surface-layer'
  | 'surface-elevation-1'
  | 'surface-elevation-2'
  | 'surface-elevation-3'
  | 'surface-gnb'
  | 'surface-gnb-gray'
  | 'surface-footer'
  | 'surface-highlight'
  | 'surface-fab'
  | 'surface-fab-pressed'
  | 'inverse-elevation-1'
  | 'inverse-elevation-2'
  | 'inverse-elevation-3'
  | 'inverse-elevation-4'
  | 'inverse-elevation-5'
  | 'inverse-elevation-6'
  | 'inverse-elevation-7'
  | 'inverse-elevation-8'
  | 'inverse-variant-1'
  | 'inverse-variant-2'
  | 'inverse-variant-3'
  | 'interaction-pressed'
  | 'interaction-selected'
  | 'interaction-focused'
  | 'interaction-hover'
  | 'disabled-variant-1'
  | 'disabled-variant-2'
  | 'disabled-variant-3'
  | 'disabled-variant-4'
  | 'disabled-variant-5'
  | 'disabled-variant-6'
  | 'disabled-variant-7'
  | 'disabled-variant-8'
  | 'on-surface-elevation-1'
  | 'on-surface-elevation-1-pressed'
  | 'on-surface-elevation-2'
  | 'on-surface-elevation-2-pressed'
  | 'on-surface-elevation-3'
  | 'on-surface-elevation-3-pressed'
  | 'on-surface-elevation-4'
  | 'on-surface-elevation-4-pressed'
  | 'neutral-variant-1'
  | 'neutral-variant-1-pressed'
  | 'neutral-variant-2'
  | 'neutral-variant-2-pressed'
  | 'neutral-variant-3'
  | 'neutral-variant-3-pressed'
  | 'neutral-variant-4'
  | 'border'
  | 'placeholder'
  | 'error'
  | 'warning'
  | 'success'
  | 'information';

export type SemanticColorTokens = Record<ColorRole, Color>;

export type ColorTheme = 'light' | 'dark';
